[env:adafruit_feather_esp32s2_tft]
platform = espressif32
board = adafruit_feather_esp32s2_tft
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson@^7.4.3
	adafruit/Adafruit GFX Library@^1.11.9
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.f_cpu = 240000000L